version: "3.8"

services:
  api:
    container_name: api
    build: .
    ports:
      - "3001:3001"
    environment:
      MONGO_URL: ${MONGO_URL}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    volumes:
      - ./src:/app/src 
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:7.0.11
    command: mongod --quiet --logpath /var/log/mongodb/mongod.log 
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongodb_data: